// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_enum.proto

package test_enum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestEnum int32

const (
	TestEnum_VALUE_ZERO TestEnum = 0
	TestEnum_VALUE_ONE  TestEnum = 1
	TestEnum_VALUE_TWO  TestEnum = 2
)

var TestEnum_name = map[int32]string{
	0: "VALUE_ZERO",
	1: "VALUE_ONE",
	2: "VALUE_TWO",
}

var TestEnum_value = map[string]int32{
	"VALUE_ZERO": 0,
	"VALUE_ONE":  1,
	"VALUE_TWO":  2,
}

func (x TestEnum) String() string {
	return proto.EnumName(TestEnum_name, int32(x))
}

func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae3cf7ce2fc27240, []int{0}
}

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	Latitude             int32    `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            int32    `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae3cf7ce2fc27240, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct {
	Result               TestEnum `protobuf:"varint,1,opt,name=result,proto3,enum=routeguide.v2.TestEnum" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae3cf7ce2fc27240, []int{1}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetResult() TestEnum {
	if m != nil {
		return m.Result
	}
	return TestEnum_VALUE_ZERO
}

func init() {
	proto.RegisterEnum("routeguide.v2.TestEnum", TestEnum_name, TestEnum_value)
	proto.RegisterType((*Point)(nil), "routeguide.v2.Point")
	proto.RegisterType((*Feature)(nil), "routeguide.v2.Feature")
}

func init() {
	proto.RegisterFile("test_enum.proto", fileDescriptor_ae3cf7ce2fc27240)
}

var fileDescriptor_ae3cf7ce2fc27240 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2d, 0x2e,
	0x89, 0x4f, 0xcd, 0x2b, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xca, 0x2f,
	0x2d, 0x49, 0x4d, 0x2f, 0xcd, 0x4c, 0x49, 0xd5, 0x2b, 0x33, 0x52, 0x72, 0xe4, 0x62, 0x0d, 0xc8,
	0xcf, 0xcc, 0x2b, 0x11, 0x92, 0xe2, 0xe2, 0xc8, 0x49, 0x2c, 0xc9, 0x2c, 0x29, 0x4d, 0x49, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x73, 0xf2, 0xf3, 0xd2,
	0x21, 0x92, 0x4c, 0x60, 0x49, 0x84, 0x80, 0x92, 0x15, 0x17, 0xbb, 0x5b, 0x6a, 0x62, 0x49, 0x69,
	0x51, 0xaa, 0x90, 0x3e, 0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0xd8, 0x08, 0x3e, 0x23,
	0x71, 0x3d, 0x14, 0xdb, 0xf4, 0x42, 0x52, 0x8b, 0x4b, 0x5c, 0xf3, 0x4a, 0x73, 0x83, 0xa0, 0xca,
	0xb4, 0x2c, 0xb8, 0x38, 0x60, 0x62, 0x42, 0x7c, 0x5c, 0x5c, 0x61, 0x8e, 0x3e, 0xa1, 0xae, 0xf1,
	0x51, 0xae, 0x41, 0xfe, 0x02, 0x0c, 0x42, 0xbc, 0x5c, 0x9c, 0x10, 0xbe, 0xbf, 0x9f, 0xab, 0x00,
	0x23, 0x82, 0x1b, 0x12, 0xee, 0x2f, 0xc0, 0x64, 0xe4, 0xca, 0xc5, 0x02, 0xd2, 0x29, 0x64, 0xcb,
	0xc5, 0xed, 0x9e, 0x5a, 0x02, 0x75, 0x80, 0x91, 0x90, 0x08, 0x9a, 0x8d, 0x60, 0xcf, 0x49, 0x89,
	0xa1, 0x89, 0x42, 0x95, 0x2b, 0x31, 0x38, 0x09, 0x47, 0x09, 0x66, 0xe6, 0xeb, 0x15, 0x24, 0x26,
	0x97, 0xe8, 0xc3, 0x43, 0x2a, 0x89, 0x0d, 0x1c, 0x54, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x56, 0x09, 0x58, 0xbf, 0x3d, 0x01, 0x00, 0x00,
}
