//! Consumer example for the creditcard plugin.
//!
//! Unlike the CSV, Protobuf and JWT examples, the plugin here does not own a content type. The
//! body is ordinary JSON, matched by the core JSON matcher, and the plugin contributes one
//! matching rule and one generator that apply to a single field inside it.

#[cfg(test)]
mod tests {
  use expectest::prelude::*;
  use pact_consumer::mock_server::StartMockServerAsync;
  use pact_consumer::prelude::*;
  use pact_models::generators::Generator;
  use serde_json::{json, Value};

  /// The Luhn check digit algorithm, so the test can assert the number it got back is a plausible
  /// card number rather than just some string - the same property the plugin's rule checks
  fn luhn_valid(number: &str) -> bool {
    let digits: Vec<u32> = number.chars().filter_map(|c| c.to_digit(10)).collect();
    if digits.len() != number.chars().filter(|c| !c.is_whitespace() && *c != '-').count() {
      return false;
    }
    let sum: u32 = digits.iter().rev().enumerate()
      .map(|(index, digit)| if index % 2 == 1 {
        let doubled = digit * 2;
        if doubled > 9 { doubled - 9 } else { doubled }
      } else {
        *digit
      })
      .sum();
    !digits.is_empty() && sum % 10 == 0
  }

  #[test_log::test(tokio::test(flavor = "multi_thread", worker_threads = 2))]
  async fn get_a_visa_card() {
    let mut builder = PactBuilder::new_v4("CreditCardClient", "CreditCardServer")
      .using_plugin("creditcard", Some("0.0.0".to_string())).await;

    builder.interaction("a request for a Visa card", "", |mut i| async move {
      i.request
        .get()
        .path("/cards/visa");
      i.response
        .ok()
        .json_utf8()
        .json_body(json_pattern!({
          "card": {
            // The plugin's rule. The provider's number does not have to be this one - it has to
            // be a Luhn-valid Visa number, which no core matching rule can express.
            "number": plugin_rule("creditcard", json_pattern!("4111111111111111"))
              .with_value("brand", "visa"),
            "expiry": term!(r"^\d{2}/\d{2}$", "04/28"),
            "brand": "visa"
          }
        }))
        // ... and the plugin's generator of the same name, so the mock server answers with a
        // freshly generated number rather than the example one
        .body_generator("$.card.number", Generator::Plugin {
          name: "creditcard".to_string(),
          values: json!({ "brand": "visa" })
        });
      i
    }).await;

    let card_service = builder.start_mock_server_async(None, None).await;

    let client = reqwest::Client::builder().build().unwrap();
    let response = client.get(format!("{}cards/visa", card_service.url()))
      .send()
      .await
      .unwrap();

    expect!(response.status().is_success()).to(be_true());
    let body: Value = response.json().await.unwrap();
    let number = body["card"]["number"].as_str().unwrap();

    // Generated by the plugin, so not necessarily the example value, but still a valid Visa
    // number: the right issuer prefix, one of the lengths Visa issues, and a good check digit
    expect!(luhn_valid(number)).to(be_true());
    expect!(number.starts_with('4')).to(be_true());
    expect!([13usize, 16, 19].contains(&number.len())).to(be_true());
  }

  #[test_log::test(tokio::test(flavor = "multi_thread", worker_threads = 2))]
  async fn the_rule_and_generator_are_written_to_the_pact_file() {
    let mut builder = PactBuilder::new_v4("CreditCardClient", "CreditCardServer")
      .using_plugin("creditcard", Some("0.0.0".to_string())).await;

    builder.interaction("a request for a Visa card", "", |mut i| async move {
      i.request.get().path("/cards/visa");
      i.response
        .ok()
        .json_utf8()
        .json_body(json_pattern!({
          "card": {
            "number": plugin_rule("creditcard", json_pattern!("4111111111111111"))
              .with_value("brand", "visa")
          }
        }))
        .body_generator("$.card.number", Generator::Plugin {
          name: "creditcard".to_string(),
          values: json!({ "brand": "visa" })
        });
      i
    }).await;

    let pact = builder.build();
    let json = pact.to_json(pact_models::PactSpecification::V4).unwrap();
    let interaction = &json["interactions"][0];

    // A plugin rule is persisted as an ordinary matching rule whose name happens to come from a
    // plugin - there is no marker in the file saying so
    expect!(&interaction["response"]["matchingRules"]["body"]["$.card.number"]["matchers"][0]).to(
      be_equal_to(&json!({ "match": "creditcard", "brand": "visa" })));
    expect!(&interaction["response"]["generators"]["body"]["$.card.number"]).to(
      be_equal_to(&json!({ "type": "creditcard", "brand": "visa" })));

    // ... and the plugin providing it is recorded, so provider verification knows to load it
    let plugins = json["metadata"]["plugins"].as_array().unwrap();
    expect!(plugins.iter().any(|plugin| plugin["name"] == json!("creditcard"))).to(be_true());
  }
}
