FROM rust:1-trixie

ARG PACT_PLUGIN_CLI_VERSION=0.3.0
ARG PACT_PLUGIN_PROTOBUF_VERSION=0.8.0

# Install deps
RUN apt clean && apt update && apt install -y git-core gcc wget protobuf-compiler

# Install pact-plugin + protobuf plugin
RUN wget https://github.com/pact-foundation/pact-plugins/releases/download/pact-plugin-cli-v${PACT_PLUGIN_CLI_VERSION}/pact-plugin-linux-x86_64.gz && gunzip pact-plugin-linux-x86_64.gz
RUN mv pact-plugin-linux-x86_64 /usr/local/bin/pact-plugin && chmod +x /usr/local/bin/pact-plugin
RUN pact-plugin -y install protobuf -v $PACT_PLUGIN_PROTOBUF_VERSION

WORKDIR /build

ENTRYPOINT [ "/bin/bash" ]
