/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.pact.grpc.example.area_calculator.consumer

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
