// Code generated by protoc-gen-go. DO NOT EDIT.
// source: area_calculator.proto

package area_calculator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShapeMessage struct {
	// Types that are valid to be assigned to Shape:
	//	*ShapeMessage_Square
	//	*ShapeMessage_Rectangle
	//	*ShapeMessage_Circle
	//	*ShapeMessage_Triangle
	//	*ShapeMessage_Parallelogram
	Shape                isShapeMessage_Shape `protobuf_oneof:"shape"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ShapeMessage) Reset()         { *m = ShapeMessage{} }
func (m *ShapeMessage) String() string { return proto.CompactTextString(m) }
func (*ShapeMessage) ProtoMessage()    {}
func (*ShapeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{0}
}

func (m *ShapeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShapeMessage.Unmarshal(m, b)
}
func (m *ShapeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShapeMessage.Marshal(b, m, deterministic)
}
func (m *ShapeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShapeMessage.Merge(m, src)
}
func (m *ShapeMessage) XXX_Size() int {
	return xxx_messageInfo_ShapeMessage.Size(m)
}
func (m *ShapeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ShapeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ShapeMessage proto.InternalMessageInfo

type isShapeMessage_Shape interface {
	isShapeMessage_Shape()
}

type ShapeMessage_Square struct {
	Square *Square `protobuf:"bytes,1,opt,name=square,proto3,oneof"`
}

type ShapeMessage_Rectangle struct {
	Rectangle *Rectangle `protobuf:"bytes,2,opt,name=rectangle,proto3,oneof"`
}

type ShapeMessage_Circle struct {
	Circle *Circle `protobuf:"bytes,3,opt,name=circle,proto3,oneof"`
}

type ShapeMessage_Triangle struct {
	Triangle *Triangle `protobuf:"bytes,4,opt,name=triangle,proto3,oneof"`
}

type ShapeMessage_Parallelogram struct {
	Parallelogram *Parallelogram `protobuf:"bytes,5,opt,name=parallelogram,proto3,oneof"`
}

func (*ShapeMessage_Square) isShapeMessage_Shape() {}

func (*ShapeMessage_Rectangle) isShapeMessage_Shape() {}

func (*ShapeMessage_Circle) isShapeMessage_Shape() {}

func (*ShapeMessage_Triangle) isShapeMessage_Shape() {}

func (*ShapeMessage_Parallelogram) isShapeMessage_Shape() {}

func (m *ShapeMessage) GetShape() isShapeMessage_Shape {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *ShapeMessage) GetSquare() *Square {
	if x, ok := m.GetShape().(*ShapeMessage_Square); ok {
		return x.Square
	}
	return nil
}

func (m *ShapeMessage) GetRectangle() *Rectangle {
	if x, ok := m.GetShape().(*ShapeMessage_Rectangle); ok {
		return x.Rectangle
	}
	return nil
}

func (m *ShapeMessage) GetCircle() *Circle {
	if x, ok := m.GetShape().(*ShapeMessage_Circle); ok {
		return x.Circle
	}
	return nil
}

func (m *ShapeMessage) GetTriangle() *Triangle {
	if x, ok := m.GetShape().(*ShapeMessage_Triangle); ok {
		return x.Triangle
	}
	return nil
}

func (m *ShapeMessage) GetParallelogram() *Parallelogram {
	if x, ok := m.GetShape().(*ShapeMessage_Parallelogram); ok {
		return x.Parallelogram
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShapeMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShapeMessage_Square)(nil),
		(*ShapeMessage_Rectangle)(nil),
		(*ShapeMessage_Circle)(nil),
		(*ShapeMessage_Triangle)(nil),
		(*ShapeMessage_Parallelogram)(nil),
	}
}

type Square struct {
	EdgeLength           float32  `protobuf:"fixed32,1,opt,name=edge_length,json=edgeLength,proto3" json:"edge_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Square) Reset()         { *m = Square{} }
func (m *Square) String() string { return proto.CompactTextString(m) }
func (*Square) ProtoMessage()    {}
func (*Square) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{1}
}

func (m *Square) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Square.Unmarshal(m, b)
}
func (m *Square) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Square.Marshal(b, m, deterministic)
}
func (m *Square) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Square.Merge(m, src)
}
func (m *Square) XXX_Size() int {
	return xxx_messageInfo_Square.Size(m)
}
func (m *Square) XXX_DiscardUnknown() {
	xxx_messageInfo_Square.DiscardUnknown(m)
}

var xxx_messageInfo_Square proto.InternalMessageInfo

func (m *Square) GetEdgeLength() float32 {
	if m != nil {
		return m.EdgeLength
	}
	return 0
}

type Rectangle struct {
	Length               float32  `protobuf:"fixed32,1,opt,name=length,proto3" json:"length,omitempty"`
	Width                float32  `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{2}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetLength() float32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Rectangle) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Circle struct {
	Radius               float32  `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{3}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type Triangle struct {
	EdgeA                float32  `protobuf:"fixed32,1,opt,name=edge_a,json=edgeA,proto3" json:"edge_a,omitempty"`
	EdgeB                float32  `protobuf:"fixed32,2,opt,name=edge_b,json=edgeB,proto3" json:"edge_b,omitempty"`
	EdgeC                float32  `protobuf:"fixed32,3,opt,name=edge_c,json=edgeC,proto3" json:"edge_c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Triangle) Reset()         { *m = Triangle{} }
func (m *Triangle) String() string { return proto.CompactTextString(m) }
func (*Triangle) ProtoMessage()    {}
func (*Triangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{4}
}

func (m *Triangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Triangle.Unmarshal(m, b)
}
func (m *Triangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Triangle.Marshal(b, m, deterministic)
}
func (m *Triangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Triangle.Merge(m, src)
}
func (m *Triangle) XXX_Size() int {
	return xxx_messageInfo_Triangle.Size(m)
}
func (m *Triangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Triangle.DiscardUnknown(m)
}

var xxx_messageInfo_Triangle proto.InternalMessageInfo

func (m *Triangle) GetEdgeA() float32 {
	if m != nil {
		return m.EdgeA
	}
	return 0
}

func (m *Triangle) GetEdgeB() float32 {
	if m != nil {
		return m.EdgeB
	}
	return 0
}

func (m *Triangle) GetEdgeC() float32 {
	if m != nil {
		return m.EdgeC
	}
	return 0
}

type Parallelogram struct {
	BaseLength           float32  `protobuf:"fixed32,1,opt,name=base_length,json=baseLength,proto3" json:"base_length,omitempty"`
	Height               float32  `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parallelogram) Reset()         { *m = Parallelogram{} }
func (m *Parallelogram) String() string { return proto.CompactTextString(m) }
func (*Parallelogram) ProtoMessage()    {}
func (*Parallelogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{5}
}

func (m *Parallelogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parallelogram.Unmarshal(m, b)
}
func (m *Parallelogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parallelogram.Marshal(b, m, deterministic)
}
func (m *Parallelogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parallelogram.Merge(m, src)
}
func (m *Parallelogram) XXX_Size() int {
	return xxx_messageInfo_Parallelogram.Size(m)
}
func (m *Parallelogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Parallelogram.DiscardUnknown(m)
}

var xxx_messageInfo_Parallelogram proto.InternalMessageInfo

func (m *Parallelogram) GetBaseLength() float32 {
	if m != nil {
		return m.BaseLength
	}
	return 0
}

func (m *Parallelogram) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type AreaRequest struct {
	Shapes               []*ShapeMessage `protobuf:"bytes,1,rep,name=shapes,proto3" json:"shapes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AreaRequest) Reset()         { *m = AreaRequest{} }
func (m *AreaRequest) String() string { return proto.CompactTextString(m) }
func (*AreaRequest) ProtoMessage()    {}
func (*AreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{6}
}

func (m *AreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaRequest.Unmarshal(m, b)
}
func (m *AreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaRequest.Marshal(b, m, deterministic)
}
func (m *AreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaRequest.Merge(m, src)
}
func (m *AreaRequest) XXX_Size() int {
	return xxx_messageInfo_AreaRequest.Size(m)
}
func (m *AreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AreaRequest proto.InternalMessageInfo

func (m *AreaRequest) GetShapes() []*ShapeMessage {
	if m != nil {
		return m.Shapes
	}
	return nil
}

type AreaResponse struct {
	Value                []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AreaResponse) Reset()         { *m = AreaResponse{} }
func (m *AreaResponse) String() string { return proto.CompactTextString(m) }
func (*AreaResponse) ProtoMessage()    {}
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96414cec5559550b, []int{7}
}

func (m *AreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaResponse.Unmarshal(m, b)
}
func (m *AreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaResponse.Marshal(b, m, deterministic)
}
func (m *AreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaResponse.Merge(m, src)
}
func (m *AreaResponse) XXX_Size() int {
	return xxx_messageInfo_AreaResponse.Size(m)
}
func (m *AreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AreaResponse proto.InternalMessageInfo

func (m *AreaResponse) GetValue() []float32 {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ShapeMessage)(nil), "area_calculator.ShapeMessage")
	proto.RegisterType((*Square)(nil), "area_calculator.Square")
	proto.RegisterType((*Rectangle)(nil), "area_calculator.Rectangle")
	proto.RegisterType((*Circle)(nil), "area_calculator.Circle")
	proto.RegisterType((*Triangle)(nil), "area_calculator.Triangle")
	proto.RegisterType((*Parallelogram)(nil), "area_calculator.Parallelogram")
	proto.RegisterType((*AreaRequest)(nil), "area_calculator.AreaRequest")
	proto.RegisterType((*AreaResponse)(nil), "area_calculator.AreaResponse")
}

func init() {
	proto.RegisterFile("area_calculator.proto", fileDescriptor_96414cec5559550b)
}

var fileDescriptor_96414cec5559550b = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x75, 0x5c, 0x62, 0xda, 0x49, 0x0a, 0xd2, 0x8a, 0xd2, 0x50, 0x15, 0xa8, 0x56, 0x1c, 0xca,
	0x25, 0x88, 0x20, 0x84, 0xe0, 0xd6, 0x04, 0x21, 0x1f, 0x28, 0x41, 0x5b, 0x4e, 0x5c, 0xaa, 0x89,
	0x33, 0xb2, 0x2d, 0x2d, 0xb1, 0xbb, 0xbb, 0x86, 0xaf, 0xe2, 0x07, 0xf8, 0x0a, 0x3e, 0x09, 0xed,
	0xae, 0x6d, 0x12, 0x5b, 0x85, 0xe3, 0x7b, 0xf3, 0xde, 0x1b, 0xcf, 0xd3, 0x1a, 0x8e, 0x50, 0x11,
	0x5e, 0x27, 0x28, 0x93, 0x4a, 0xa2, 0x29, 0xd4, 0xb4, 0x54, 0x85, 0x29, 0xd8, 0xfd, 0x0e, 0xcd,
	0x7f, 0x85, 0x30, 0xbe, 0xca, 0xb0, 0xa4, 0x4b, 0xd2, 0x1a, 0x53, 0x62, 0x2f, 0x21, 0xd2, 0x37,
	0x15, 0x2a, 0x9a, 0x0c, 0xce, 0x06, 0xe7, 0xa3, 0xd9, 0xf1, 0xb4, 0x9b, 0x74, 0xe5, 0xc6, 0x71,
	0x20, 0x6a, 0x21, 0x7b, 0x07, 0x07, 0x8a, 0x12, 0x83, 0x9b, 0x54, 0xd2, 0x24, 0x74, 0xae, 0x93,
	0x9e, 0x4b, 0x34, 0x8a, 0x38, 0x10, 0x7f, 0xe5, 0x76, 0x5d, 0x92, 0xab, 0x44, 0xd2, 0x64, 0xef,
	0x96, 0x75, 0x0b, 0x37, 0xb6, 0xeb, 0xbc, 0x90, 0xbd, 0x81, 0x7d, 0xa3, 0x72, 0xbf, 0xed, 0x8e,
	0x33, 0x3d, 0xea, 0x99, 0xbe, 0xd4, 0x82, 0x38, 0x10, 0xad, 0x98, 0x7d, 0x80, 0xc3, 0x12, 0x15,
	0x4a, 0x49, 0xb2, 0x48, 0x15, 0x7e, 0x9b, 0x0c, 0x9d, 0xfb, 0x49, 0xcf, 0xfd, 0x79, 0x5b, 0x15,
	0x07, 0x62, 0xd7, 0x36, 0xbf, 0x0b, 0x43, 0x6d, 0x2b, 0xe3, 0xcf, 0x21, 0xf2, 0x65, 0xb0, 0xa7,
	0x30, 0xa2, 0x75, 0x4a, 0xd7, 0x92, 0x36, 0xa9, 0xc9, 0x5c, 0x75, 0xa1, 0x00, 0x4b, 0x7d, 0x74,
	0x0c, 0x7f, 0x0b, 0x07, 0x6d, 0x03, 0xec, 0x21, 0x44, 0x3b, 0xc2, 0x1a, 0xb1, 0x07, 0x30, 0xfc,
	0x91, 0xaf, 0x4d, 0xe6, 0x4a, 0x0c, 0x85, 0x07, 0xfc, 0x0c, 0x22, 0xdf, 0x81, 0xf5, 0x29, 0x5c,
	0xe7, 0x95, 0x6e, 0x7c, 0x1e, 0xf1, 0x25, 0xec, 0x37, 0x07, 0xb3, 0x23, 0x88, 0xdc, 0x97, 0x60,
	0xad, 0x19, 0x5a, 0x74, 0xd1, 0xd2, 0xab, 0x26, 0xdb, 0xa2, 0x79, 0x4b, 0x27, 0xae, 0xfe, 0x9a,
	0x5e, 0xf0, 0x18, 0x0e, 0x77, 0x3a, 0xb0, 0xf7, 0xad, 0x50, 0x77, 0xef, 0xb3, 0x94, 0xbf, 0xcf,
	0x7e, 0x5a, 0x46, 0x79, 0x9a, 0x99, 0x3a, 0xbf, 0x46, 0xfc, 0x3d, 0x8c, 0x2e, 0x14, 0xa1, 0xa0,
	0x9b, 0x8a, 0xb4, 0x61, 0xaf, 0x21, 0x72, 0xd5, 0xd9, 0x0b, 0xf6, 0xce, 0x47, 0xb3, 0xc7, 0xfd,
	0xd7, 0xb5, 0xf5, 0x18, 0x45, 0x2d, 0xe6, 0xcf, 0x60, 0xec, 0x53, 0x74, 0x59, 0x6c, 0x34, 0xd9,
	0xa2, 0xbe, 0xa3, 0xac, 0xc8, 0xa5, 0x84, 0xc2, 0x83, 0xd9, 0xcf, 0x01, 0xc0, 0xa2, 0x4d, 0x62,
	0x9f, 0x60, 0xdc, 0xe4, 0xd2, 0x72, 0x43, 0xec, 0xdf, 0xbb, 0x4e, 0xfa, 0xe3, 0xed, 0x95, 0x3c,
	0x60, 0x4b, 0xb8, 0xd7, 0xe6, 0x5d, 0x56, 0xd2, 0xe4, 0xec, 0xf4, 0x16, 0x8b, 0xbb, 0xf5, 0xbf,
	0x81, 0xf3, 0xd3, 0xaf, 0xc7, 0x79, 0x31, 0x2d, 0x31, 0x31, 0x2f, 0x3a, 0xca, 0xdf, 0xe1, 0x60,
	0x15, 0xb9, 0x3f, 0xf6, 0xd5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe2, 0x5c, 0x5e, 0xca,
	0x03, 0x00, 0x00,
}
