// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: area_calculator.proto

package area_calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Shape:
	//
	//	*ShapeMessage_Square
	//	*ShapeMessage_Rectangle
	//	*ShapeMessage_Circle
	//	*ShapeMessage_Triangle
	//	*ShapeMessage_Parallelogram
	Shape         isShapeMessage_Shape `protobuf_oneof:"shape"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShapeMessage) Reset() {
	*x = ShapeMessage{}
	mi := &file_area_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeMessage) ProtoMessage() {}

func (x *ShapeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeMessage.ProtoReflect.Descriptor instead.
func (*ShapeMessage) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *ShapeMessage) GetShape() isShapeMessage_Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *ShapeMessage) GetSquare() *Square {
	if x != nil {
		if x, ok := x.Shape.(*ShapeMessage_Square); ok {
			return x.Square
		}
	}
	return nil
}

func (x *ShapeMessage) GetRectangle() *Rectangle {
	if x != nil {
		if x, ok := x.Shape.(*ShapeMessage_Rectangle); ok {
			return x.Rectangle
		}
	}
	return nil
}

func (x *ShapeMessage) GetCircle() *Circle {
	if x != nil {
		if x, ok := x.Shape.(*ShapeMessage_Circle); ok {
			return x.Circle
		}
	}
	return nil
}

func (x *ShapeMessage) GetTriangle() *Triangle {
	if x != nil {
		if x, ok := x.Shape.(*ShapeMessage_Triangle); ok {
			return x.Triangle
		}
	}
	return nil
}

func (x *ShapeMessage) GetParallelogram() *Parallelogram {
	if x != nil {
		if x, ok := x.Shape.(*ShapeMessage_Parallelogram); ok {
			return x.Parallelogram
		}
	}
	return nil
}

type isShapeMessage_Shape interface {
	isShapeMessage_Shape()
}

type ShapeMessage_Square struct {
	Square *Square `protobuf:"bytes,1,opt,name=square,proto3,oneof"`
}

type ShapeMessage_Rectangle struct {
	Rectangle *Rectangle `protobuf:"bytes,2,opt,name=rectangle,proto3,oneof"`
}

type ShapeMessage_Circle struct {
	Circle *Circle `protobuf:"bytes,3,opt,name=circle,proto3,oneof"`
}

type ShapeMessage_Triangle struct {
	Triangle *Triangle `protobuf:"bytes,4,opt,name=triangle,proto3,oneof"`
}

type ShapeMessage_Parallelogram struct {
	Parallelogram *Parallelogram `protobuf:"bytes,5,opt,name=parallelogram,proto3,oneof"`
}

func (*ShapeMessage_Square) isShapeMessage_Shape() {}

func (*ShapeMessage_Rectangle) isShapeMessage_Shape() {}

func (*ShapeMessage_Circle) isShapeMessage_Shape() {}

func (*ShapeMessage_Triangle) isShapeMessage_Shape() {}

func (*ShapeMessage_Parallelogram) isShapeMessage_Shape() {}

type Square struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeLength    float32                `protobuf:"fixed32,1,opt,name=edge_length,json=edgeLength,proto3" json:"edge_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Square) Reset() {
	*x = Square{}
	mi := &file_area_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Square) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Square) ProtoMessage() {}

func (x *Square) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Square.ProtoReflect.Descriptor instead.
func (*Square) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Square) GetEdgeLength() float32 {
	if x != nil {
		return x.EdgeLength
	}
	return 0
}

type Rectangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float32                `protobuf:"fixed32,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         float32                `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_area_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *Rectangle) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Rectangle) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type Circle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radius        float32                `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Circle) Reset() {
	*x = Circle{}
	mi := &file_area_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Circle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circle) ProtoMessage() {}

func (x *Circle) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circle.ProtoReflect.Descriptor instead.
func (*Circle) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *Circle) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type Triangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeA         float32                `protobuf:"fixed32,1,opt,name=edge_a,json=edgeA,proto3" json:"edge_a,omitempty"`
	EdgeB         float32                `protobuf:"fixed32,2,opt,name=edge_b,json=edgeB,proto3" json:"edge_b,omitempty"`
	EdgeC         float32                `protobuf:"fixed32,3,opt,name=edge_c,json=edgeC,proto3" json:"edge_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Triangle) Reset() {
	*x = Triangle{}
	mi := &file_area_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triangle) ProtoMessage() {}

func (x *Triangle) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triangle.ProtoReflect.Descriptor instead.
func (*Triangle) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *Triangle) GetEdgeA() float32 {
	if x != nil {
		return x.EdgeA
	}
	return 0
}

func (x *Triangle) GetEdgeB() float32 {
	if x != nil {
		return x.EdgeB
	}
	return 0
}

func (x *Triangle) GetEdgeC() float32 {
	if x != nil {
		return x.EdgeC
	}
	return 0
}

type Parallelogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseLength    float32                `protobuf:"fixed32,1,opt,name=base_length,json=baseLength,proto3" json:"base_length,omitempty"`
	Height        float32                `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parallelogram) Reset() {
	*x = Parallelogram{}
	mi := &file_area_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parallelogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parallelogram) ProtoMessage() {}

func (x *Parallelogram) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parallelogram.ProtoReflect.Descriptor instead.
func (*Parallelogram) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *Parallelogram) GetBaseLength() float32 {
	if x != nil {
		return x.BaseLength
	}
	return 0
}

func (x *Parallelogram) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shapes        []*ShapeMessage        `protobuf:"bytes,1,rep,name=shapes,proto3" json:"shapes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRequest) Reset() {
	*x = AreaRequest{}
	mi := &file_area_calculator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRequest) ProtoMessage() {}

func (x *AreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRequest.ProtoReflect.Descriptor instead.
func (*AreaRequest) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{6}
}

func (x *AreaRequest) GetShapes() []*ShapeMessage {
	if x != nil {
		return x.Shapes
	}
	return nil
}

type AreaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Value             []float32              `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	NestedFieldLevel1 []*NestedFieldLevel1   `protobuf:"bytes,2,rep,name=nestedFieldLevel1,proto3" json:"nestedFieldLevel1,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AreaResponse) Reset() {
	*x = AreaResponse{}
	mi := &file_area_calculator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaResponse) ProtoMessage() {}

func (x *AreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaResponse.ProtoReflect.Descriptor instead.
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{7}
}

func (x *AreaResponse) GetValue() []float32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AreaResponse) GetNestedFieldLevel1() []*NestedFieldLevel1 {
	if x != nil {
		return x.NestedFieldLevel1
	}
	return nil
}

type NestedFieldLevel1 struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	FirstLevel    string                                 `protobuf:"bytes,1,opt,name=FirstLevel,proto3" json:"FirstLevel,omitempty"`
	InnerLevels   []*NestedFieldLevel1_NestedFieldLevel2 `protobuf:"bytes,2,rep,name=InnerLevels,proto3" json:"InnerLevels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedFieldLevel1) Reset() {
	*x = NestedFieldLevel1{}
	mi := &file_area_calculator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedFieldLevel1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedFieldLevel1) ProtoMessage() {}

func (x *NestedFieldLevel1) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedFieldLevel1.ProtoReflect.Descriptor instead.
func (*NestedFieldLevel1) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{8}
}

func (x *NestedFieldLevel1) GetFirstLevel() string {
	if x != nil {
		return x.FirstLevel
	}
	return ""
}

func (x *NestedFieldLevel1) GetInnerLevels() []*NestedFieldLevel1_NestedFieldLevel2 {
	if x != nil {
		return x.InnerLevels
	}
	return nil
}

type NestedFieldLevel1_NestedFieldLevel2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerLevel    string                 `protobuf:"bytes,1,opt,name=InnerLevel,proto3" json:"InnerLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedFieldLevel1_NestedFieldLevel2) Reset() {
	*x = NestedFieldLevel1_NestedFieldLevel2{}
	mi := &file_area_calculator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedFieldLevel1_NestedFieldLevel2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedFieldLevel1_NestedFieldLevel2) ProtoMessage() {}

func (x *NestedFieldLevel1_NestedFieldLevel2) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedFieldLevel1_NestedFieldLevel2.ProtoReflect.Descriptor instead.
func (*NestedFieldLevel1_NestedFieldLevel2) Descriptor() ([]byte, []int) {
	return file_area_calculator_proto_rawDescGZIP(), []int{8, 0}
}

func (x *NestedFieldLevel1_NestedFieldLevel2) GetInnerLevel() string {
	if x != nil {
		return x.InnerLevel
	}
	return ""
}

var File_area_calculator_proto protoreflect.FileDescriptor

const file_area_calculator_proto_rawDesc = "" +
	"\n" +
	"\x15area_calculator.proto\x12\x0farea_calculator\"\xba\x02\n" +
	"\fShapeMessage\x121\n" +
	"\x06square\x18\x01 \x01(\v2\x17.area_calculator.SquareH\x00R\x06square\x12:\n" +
	"\trectangle\x18\x02 \x01(\v2\x1a.area_calculator.RectangleH\x00R\trectangle\x121\n" +
	"\x06circle\x18\x03 \x01(\v2\x17.area_calculator.CircleH\x00R\x06circle\x127\n" +
	"\btriangle\x18\x04 \x01(\v2\x19.area_calculator.TriangleH\x00R\btriangle\x12F\n" +
	"\rparallelogram\x18\x05 \x01(\v2\x1e.area_calculator.ParallelogramH\x00R\rparallelogramB\a\n" +
	"\x05shape\")\n" +
	"\x06Square\x12\x1f\n" +
	"\vedge_length\x18\x01 \x01(\x02R\n" +
	"edgeLength\"9\n" +
	"\tRectangle\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x02R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x02R\x05width\" \n" +
	"\x06Circle\x12\x16\n" +
	"\x06radius\x18\x01 \x01(\x02R\x06radius\"O\n" +
	"\bTriangle\x12\x15\n" +
	"\x06edge_a\x18\x01 \x01(\x02R\x05edgeA\x12\x15\n" +
	"\x06edge_b\x18\x02 \x01(\x02R\x05edgeB\x12\x15\n" +
	"\x06edge_c\x18\x03 \x01(\x02R\x05edgeC\"H\n" +
	"\rParallelogram\x12\x1f\n" +
	"\vbase_length\x18\x01 \x01(\x02R\n" +
	"baseLength\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x02R\x06height\"D\n" +
	"\vAreaRequest\x125\n" +
	"\x06shapes\x18\x01 \x03(\v2\x1d.area_calculator.ShapeMessageR\x06shapes\"v\n" +
	"\fAreaResponse\x12\x14\n" +
	"\x05value\x18\x01 \x03(\x02R\x05value\x12P\n" +
	"\x11nestedFieldLevel1\x18\x02 \x03(\v2\".area_calculator.NestedFieldLevel1R\x11nestedFieldLevel1\"\xc0\x01\n" +
	"\x11NestedFieldLevel1\x12\x1e\n" +
	"\n" +
	"FirstLevel\x18\x01 \x01(\tR\n" +
	"FirstLevel\x12V\n" +
	"\vInnerLevels\x18\x02 \x03(\v24.area_calculator.NestedFieldLevel1.NestedFieldLevel2R\vInnerLevels\x1a3\n" +
	"\x11NestedFieldLevel2\x12\x1e\n" +
	"\n" +
	"InnerLevel\x18\x01 \x01(\tR\n" +
	"InnerLevel2\xad\x01\n" +
	"\n" +
	"Calculator\x12N\n" +
	"\fcalculateOne\x12\x1d.area_calculator.ShapeMessage\x1a\x1d.area_calculator.AreaResponse\"\x00\x12O\n" +
	"\x0ecalculateMulti\x12\x1c.area_calculator.AreaRequest\x1a\x1d.area_calculator.AreaResponse\"\x00B\x19Z\x17io.pact/area_calculatorb\x06proto3"

var (
	file_area_calculator_proto_rawDescOnce sync.Once
	file_area_calculator_proto_rawDescData []byte
)

func file_area_calculator_proto_rawDescGZIP() []byte {
	file_area_calculator_proto_rawDescOnce.Do(func() {
		file_area_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_area_calculator_proto_rawDesc), len(file_area_calculator_proto_rawDesc)))
	})
	return file_area_calculator_proto_rawDescData
}

var file_area_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_area_calculator_proto_goTypes = []any{
	(*ShapeMessage)(nil),                        // 0: area_calculator.ShapeMessage
	(*Square)(nil),                              // 1: area_calculator.Square
	(*Rectangle)(nil),                           // 2: area_calculator.Rectangle
	(*Circle)(nil),                              // 3: area_calculator.Circle
	(*Triangle)(nil),                            // 4: area_calculator.Triangle
	(*Parallelogram)(nil),                       // 5: area_calculator.Parallelogram
	(*AreaRequest)(nil),                         // 6: area_calculator.AreaRequest
	(*AreaResponse)(nil),                        // 7: area_calculator.AreaResponse
	(*NestedFieldLevel1)(nil),                   // 8: area_calculator.NestedFieldLevel1
	(*NestedFieldLevel1_NestedFieldLevel2)(nil), // 9: area_calculator.NestedFieldLevel1.NestedFieldLevel2
}
var file_area_calculator_proto_depIdxs = []int32{
	1,  // 0: area_calculator.ShapeMessage.square:type_name -> area_calculator.Square
	2,  // 1: area_calculator.ShapeMessage.rectangle:type_name -> area_calculator.Rectangle
	3,  // 2: area_calculator.ShapeMessage.circle:type_name -> area_calculator.Circle
	4,  // 3: area_calculator.ShapeMessage.triangle:type_name -> area_calculator.Triangle
	5,  // 4: area_calculator.ShapeMessage.parallelogram:type_name -> area_calculator.Parallelogram
	0,  // 5: area_calculator.AreaRequest.shapes:type_name -> area_calculator.ShapeMessage
	8,  // 6: area_calculator.AreaResponse.nestedFieldLevel1:type_name -> area_calculator.NestedFieldLevel1
	9,  // 7: area_calculator.NestedFieldLevel1.InnerLevels:type_name -> area_calculator.NestedFieldLevel1.NestedFieldLevel2
	0,  // 8: area_calculator.Calculator.calculateOne:input_type -> area_calculator.ShapeMessage
	6,  // 9: area_calculator.Calculator.calculateMulti:input_type -> area_calculator.AreaRequest
	7,  // 10: area_calculator.Calculator.calculateOne:output_type -> area_calculator.AreaResponse
	7,  // 11: area_calculator.Calculator.calculateMulti:output_type -> area_calculator.AreaResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_area_calculator_proto_init() }
func file_area_calculator_proto_init() {
	if File_area_calculator_proto != nil {
		return
	}
	file_area_calculator_proto_msgTypes[0].OneofWrappers = []any{
		(*ShapeMessage_Square)(nil),
		(*ShapeMessage_Rectangle)(nil),
		(*ShapeMessage_Circle)(nil),
		(*ShapeMessage_Triangle)(nil),
		(*ShapeMessage_Parallelogram)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_area_calculator_proto_rawDesc), len(file_area_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_area_calculator_proto_goTypes,
		DependencyIndexes: file_area_calculator_proto_depIdxs,
		MessageInfos:      file_area_calculator_proto_msgTypes,
	}.Build()
	File_area_calculator_proto = out.File
	file_area_calculator_proto_goTypes = nil
	file_area_calculator_proto_depIdxs = nil
}
