package io.pact.plugins.examples.creditcard;

import au.com.dius.pact.consumer.MockServer;
import au.com.dius.pact.consumer.dsl.PactBuilder;
import au.com.dius.pact.consumer.dsl.PactDslJsonBody;
import au.com.dius.pact.consumer.dsl.PluginRuleMatcher;
import au.com.dius.pact.consumer.junit5.PactConsumerTestExt;
import au.com.dius.pact.consumer.junit5.PactTestFor;
import au.com.dius.pact.core.model.V4Pact;
import au.com.dius.pact.core.model.annotations.Pact;
import au.com.dius.pact.core.support.json.JsonValue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

/**
 * Consumer example for the creditcard plugin.
 *
 * Unlike the CSV, Protobuf and JWT examples, the plugin here does not own a content type. The body
 * is ordinary JSON, matched by the core JSON matcher, and the plugin contributes one matching rule
 * and one generator that apply to a single field inside it.
 */
@ExtendWith(PactConsumerTestExt.class)
class CreditCardClientTest {

  @Pact(consumer = "CreditCardClient")
  V4Pact pact(PactBuilder builder) {
    return builder
      .usingPlugin("creditcard", "0.0.0")
      .expectsToReceive("a request for a Visa card", "core/transport/http")
      .with(Map.of(
        "request.path", "/cards/visa",
        "request.method", "GET",
        "response.status", "200",
        "response.contents", Map.of(
          "pact:content-type", "application/json",
          "body", new PactDslJsonBody()
            .object("card")
            // The plugin's rule and, because the matcher was built with generate = true, its
            // generator of the same name. The provider's number does not have to be this one - it
            // has to be a Luhn-valid Visa number, which no core matching rule can express.
            .pluginValue("number", new PluginRuleMatcher(
              "creditcard",
              "4111111111111111",
              Map.of("brand", new JsonValue.StringValue("visa")),
              true
            ))
            .stringMatcher("expiry", "^\\d{2}/\\d{2}$", "04/28")
            .stringValue("brand", "visa")
            .closeObject()
        )
      ))
      .toPact();
  }

  @Test
  @PactTestFor(providerName = "CreditCardServer", pactMethod = "pact")
  void getAVisaCard(MockServer mockServer) throws Exception {
    HttpResponse<String> response = HttpClient.newHttpClient().send(
      HttpRequest.newBuilder(URI.create(mockServer.getUrl() + "/cards/visa")).GET().build(),
      HttpResponse.BodyHandlers.ofString()
    );

    assertThat(response.statusCode(), is(200));

    String number = numberFrom(response.body());
    // Generated by the plugin, so not necessarily the example value, but still a valid Visa number:
    // the right issuer prefix, one of the lengths Visa issues, and a good check digit
    assertThat(luhnValid(number), is(true));
    assertThat(number.startsWith("4"), is(true));
    assertThat(List.of(13, 16, 19).contains(number.length()), is(true));
  }

  private static String numberFrom(String body) {
    int start = body.indexOf("\"number\"");
    int open = body.indexOf('"', body.indexOf(':', start)) + 1;
    return body.substring(open, body.indexOf('"', open));
  }

  /**
   * The Luhn check digit algorithm, so the test can assert the number it got back is a plausible
   * card number rather than just some string - the same property the plugin's rule checks
   */
  private static boolean luhnValid(String number) {
    int sum = 0;
    for (int index = 0; index < number.length(); index++) {
      char ch = number.charAt(number.length() - 1 - index);
      if (!Character.isDigit(ch)) {
        return false;
      }
      int digit = Character.getNumericValue(ch);
      if (index % 2 == 1) {
        digit *= 2;
        if (digit > 9) {
          digit -= 9;
        }
      }
      sum += digit;
    }
    return !number.isEmpty() && sum % 10 == 0;
  }
}
